version: "3"

services:
  redis:
    container_name: gifty-redis-prod
    build:
      dockerfile: Dockerfile
      context: ./config/redis/prod
    image: limhwasup/gifty-redis-prod
    ports:
      - "6379:6379"

#  maria:
#    container_name: gifty-maria
#    build:
#      dockerfile: Dockerfile
#      context: ./config/database
#    image: limhwasup/gifty-maria
#    environment:
#      - MARIADB_DATABASE=gifty-mariadb
#      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#    ports:
#      - "3307:3306"

  backend-prod:
    image: limhwasup/gifty-server-prod
    build:
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    hostname: backend-prod
    expose:
      - "8080"

  nginx:
    container_name: gifty-nginx-prod
    image: limhwasup/gifty-nginx-prod
    build:
      dockerfile: Dockerfile
      context: ./config/nginx/prod
    depends_on:
      - redis
      - backend-prod
#    volumes:
#      - ./config/nginx/prod:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always
