server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none => create 는 서버 켤때마다 데이터 날라감
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 740879351879-kr1heqpsa0jiv6j7p22fg4sfk1sjft1v.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 3221821591372128
            client-secret: 3eeeb584acce22b235c966b74e09b066
            scope:
            - email
            - public_profile
# 구글이나 페이스북은 redirect-url 이 기본적으로 설정 되어 있음 => http://localhost:8080/login/oauth2/code/(google, facebook)
          naver:
            client-id: J7K0OiQTWz4UEUh9R6lc
            client-secret: HNs9irTnsw
            scope:
              - name
              - email
            client-name: Naver # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.







